package types

import "github.com/SHREYANSHSINGH14/raft"

// This file is hand-written; everything else in this package is generated by
// scripts/generate_protos.sh. It is the single place the embedding translates
// between the library's plain Go structs and this embedding's proto types.
//
// It lives here rather than in db/ or server/ because both of those need it and
// neither owns it: db uses it at the storage boundary, server at the gRPC
// boundary. Having exactly one implementation is the point — the same mapping
// was previously written out by hand at three call sites, and a field omitted
// from one of them was invisible at the other two.
//
// The library never imports this package, so the dependency still only points
// inward (see CLAUDE.md).

// The two enums are offset by one and must be mapped explicitly, never cast:
// proto reserves 0 for UNSPECIFIED, while the library's EntryType_Command is
// iota. A cast would turn every Config entry into a NoOp — silently, since both
// are valid values.
//
// ENTRY_TYPE_UNSPECIFIED maps to EntryType_Command because that is what entries
// written before Type was carried already decode to: their Type field is absent,
// which reads back as 0. The library has no Unspecified value to map it to.
func entryTypeToRaft(t EntryType) raft.EntryType {
	switch t {
	case EntryType_ENTRY_TYPE_NO_OP:
		return raft.EntryType_NoOp
	case EntryType_ENTRY_TYPE_CONFIG:
		return raft.EntryType_Config
	case EntryType_ENTRY_TYPE_BARRIER:
		return raft.EntryType_Barrier
	default: // ENTRY_TYPE_COMMAND, ENTRY_TYPE_UNSPECIFIED, anything unknown
		return raft.EntryType_Command
	}
}

func entryTypeFromRaft(t raft.EntryType) EntryType {
	switch t {
	case raft.EntryType_NoOp:
		return EntryType_ENTRY_TYPE_NO_OP
	case raft.EntryType_Config:
		return EntryType_ENTRY_TYPE_CONFIG
	case raft.EntryType_Barrier:
		return EntryType_ENTRY_TYPE_BARRIER
	default:
		return EntryType_ENTRY_TYPE_COMMAND
	}
}

// LogEntryToRaft converts a wire/storage entry into the library's LogEntry.
func LogEntryToRaft(p *LogEntry) raft.LogEntry {
	if p == nil {
		return raft.LogEntry{}
	}
	return raft.LogEntry{
		Index: p.Index,
		Term:  p.Term,
		Type:  entryTypeToRaft(p.Type),
		Data:  p.Data,
	}
}

// LogEntryFromRaft converts the library's LogEntry into a wire/storage entry.
func LogEntryFromRaft(e raft.LogEntry) *LogEntry {
	return &LogEntry{
		Index: e.Index,
		Term:  e.Term,
		Type:  entryTypeFromRaft(e.Type),
		Data:  e.Data,
	}
}

// LogEntriesToRaft converts a slice, preserving order.
func LogEntriesToRaft(ps []*LogEntry) []raft.LogEntry {
	out := make([]raft.LogEntry, len(ps))
	for i, p := range ps {
		out[i] = LogEntryToRaft(p)
	}
	return out
}

// LogEntriesFromRaft converts a slice, preserving order.
func LogEntriesFromRaft(es []raft.LogEntry) []*LogEntry {
	out := make([]*LogEntry, len(es))
	for i, e := range es {
		out[i] = LogEntryFromRaft(e)
	}
	return out
}
