package types

import "github.com/SHREYANSHSINGH14/raft"

// This file is hand-written; everything else in this package is generated by
// scripts/generate_protos.sh. It is the single place the embedding translates
// between the library's plain Go structs and this embedding's proto types.
//
// It lives here rather than in db/ or server/ because both of those need it and
// neither owns it: db uses it at the storage boundary, server at the gRPC
// boundary. Having exactly one implementation is the point — the same mapping
// was previously written out by hand at three call sites, and a field omitted
// from one of them was invisible at the other two.
//
// The library never imports this package, so the dependency still only points
// inward (see CLAUDE.md).

// LogEntryToRaft converts a wire/storage entry into the library's LogEntry.
func LogEntryToRaft(p *LogEntry) raft.LogEntry {
	if p == nil {
		return raft.LogEntry{}
	}
	return raft.LogEntry{
		Index: p.Index,
		Term:  p.Term,
		Data:  p.Data,
	}
}

// LogEntryFromRaft converts the library's LogEntry into a wire/storage entry.
func LogEntryFromRaft(e raft.LogEntry) *LogEntry {
	return &LogEntry{
		Index: e.Index,
		Term:  e.Term,
		Data:  e.Data,
	}
}

// LogEntriesToRaft converts a slice, preserving order.
func LogEntriesToRaft(ps []*LogEntry) []raft.LogEntry {
	out := make([]raft.LogEntry, len(ps))
	for i, p := range ps {
		out[i] = LogEntryToRaft(p)
	}
	return out
}

// LogEntriesFromRaft converts a slice, preserving order.
func LogEntriesFromRaft(es []raft.LogEntry) []*LogEntry {
	out := make([]*LogEntry, len(es))
	for i, e := range es {
		out[i] = LogEntryFromRaft(e)
	}
	return out
}
